:8080 {
	bind 172.31.250.3
	@unknownHost not host tuannguyenviet.site
	handle @unknownHost {
		respond 404
	}

	log {
		output stdout
		format filter {
			wrap json
			fields {
				request>headers>Authorization delete
				request>headers>Cookie delete
				request>uri delete
			}
		}
	}

	@notTunnel not remote_ip 172.31.250.2/32
	handle @notTunnel {
		respond 403
	}

	@unsupported not method GET HEAD
	handle @unsupported {
		header Allow "GET, HEAD"
		respond 405
	}

	request_body {
		max_size 1MB
	}

	reverse_proxy portfolio-web:8080 {
		header_up X-Forwarded-Proto https
		transport http {
			dial_timeout 3s
			response_header_timeout 10s
		}
	}
}
